name: Pull Request Labels
on:
  pull_request:
    branches:
      - master
      - release-*
    types: [labeled, unlabeled]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "type/bug-fix, type/enhancement, type/new-feature, type/testing"
